# Site settings
title: 青衫 Aspie
description: >-
  因为你我，这个世界终将丰富精彩！
typing: >-


baseurl: ""
url: ""
repository: QingShanAspie/QingShanAspie.Github.io

markdown: kramdown

author:
  name     : 青衫 Aspie
  email    : qingshan_aspie@126.com
  github   : QingShanAspie
  wxmp     : s?__biz=MzIyMzgyMjY5NQ==&mid=2247483668&idx=2&sn=dce6ec69066d00eec50cdfc2adf87bcb&chksm=e819171cdf6e9e0a53bc87fbcbbddd1868fc44f0d60965ab51a69ba8d98e71dd2494b0f03627&scene=21#wechat_redirect
  zhihu    : qing-shan-83-9-38

defaults:
  - scope:
      path: ""
      type: "Scale"
    values:
      layout: "page"

permalink: articles/:title

exclude:
- README.md
- CONTRIBUTING.md
- LICENSE
- Gemfile
- Gemfile.lock
