title: 青衫 Aspie
description: >-
  青衫 Aspie ｜ 致力于孤独症谱系权威资讯资源
typing: >-
  因为你我，这个世界终将丰富多彩！
baseurl: ""
url: ""
repository: QingShanAspie/QingShanAspie.Github.io

debug: 0

version: 0.1

markdown: kramdown

author:
  name     : 青衫 Aspie
  email    : qingshan_aspie@126.com
  github   : 
  wxmp     : https://mp.weixin.qq.com/s?__biz=MzIyMzgyMjY5NQ==&mid=2247483668&idx=2&sn=dce6ec69066d00eec50cdfc2adf87bcb&chksm=e819171cdf6e9e0a53bc87fbcbbddd1868fc44f0d60965ab51a69ba8d98e71dd2494b0f03627&scene=21#wechat_redirect
  zhihu    : qing-shan-83-9-38

collections:
  quotients:
    output: true
    permalink: /Quotients/:name
  news:
    output: true
    permalink: /News/:name

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: [local]
  blanklines: false
  profile: false
  startings: [html, head, body]

defaults:
  - scope:
      path: ""
      type: "quotients"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "news"
    values:
      layout: "post"


permalink: Articles/:title

sass:
    sass_dir: _sass
    style: compressed


exclude:
- README.md
- CONTRIBUTING.md
- LICENSE
- Gemfile
- Gemfile.lock
- Readme_DEV.md

